from .models import Scheme

SCHEMES = [
    Scheme(
        id="demo-nsp-pg",
        name="National Scholarship Demo – Post-Matric",
        authority="SchemeAI Demo Dataset",
        description="Demonstration education scholarship record for testing the eligibility workflow.",
        education_levels=["UG", "PG", "DIPLOMA"],
        min_age=16,
        max_age=35,
        max_income=250000,
        categories=["SC", "ST", "OBC", "GENERAL"],
        benefit="Tuition and maintenance assistance (demo value).",
        documents=["Income certificate", "College ID", "Academic certificate"],
        source="Demo knowledge base",
        source_page="1",
        source_text="Demo rule: applicants aged 16–35 with annual family income up to INR 250000 studying UG, PG or diploma courses may be considered.",
    ),
    Scheme(
        id="demo-karnataka-merit",
        name="Karnataka Student Merit Support – Demo",
        authority="SchemeAI Demo Dataset",
        description="Demonstration Karnataka education support record for testing state matching.",
        state="Karnataka",
        education_levels=["UG"],
        min_age=17,
        max_age=30,
        max_income=500000,
        benefit="Education support (demo value).",
        documents=["Domicile proof", "College ID", "Marks card"],
        source="Demo knowledge base",
        source_page="2",
        source_text="Demo rule: Karnataka residents enrolled in undergraduate study, aged 17–30 with annual family income up to INR 500000 may be considered.",
    ),
    Scheme(
        id="demo-disability-support",
        name="Higher Education Accessibility Support – Demo",
        authority="SchemeAI Demo Dataset",
        description="Demonstration accessibility-focused education support record.",
        education_levels=["UG", "PG"],
        min_age=17,
        max_age=40,
        disability_required=True,
        benefit="Accessibility and educational support (demo value).",
        documents=["Disability certificate", "College ID", "Academic certificate"],
        source="Demo knowledge base",
        source_page="3",
        source_text="Demo rule: students with a documented disability enrolled in UG or PG study may be considered.",
    ),
]
